### ISSUE TITLE
Having trouble with pre-race menu disappearing

### ISSUE THREAD

**Issue by AvengerJ** [ddm999/ClubmanSharp#51]
I move to the pre-race menu on the ps5 but when I connect via remote play, it disappears and goes into an attract or demo mode.  I think the utility needs the pre-race menu visible.  Am I doing something wrong?

**Comment by ddm999** [comment]
When the menu disappears during pre-race, it reappears on any button input so that doesn't affect the bot at all.

From the sounds of it, the bot isn't getting any inputs to remote play:
read everything here https://github.com/ddm999/ClubmanSharp/wiki#update-for-remote-play-v60 (under the "Update for Remote Play v6.0" heading) and follow those instructions to patch your remote play & it should start working.

If you've already tried using the auto-patcher built into the main page of ClubmanSharp and it doesn't work, something's going wrong with it and you'll have to manually patch using the links at the bottom of that section.

**Comment by Photon-Phoenix** [comment]
> I move to the pre-race menu on the ps5 but when I connect via remote play, it disappears and goes into an attract or demo mode. I think the utility needs the pre-race menu visible. Am I doing something wrong?

This is caused by no controller inputs which implies Remote Play is not a patched 5.5.0 install. 6.0, the current version, has an incompatibility issue with the virtual controller we're using. (Fix coming soon).  For now there's a workaround.

https://github.com/ddm999/ClubmanSharp/wiki#update-for-remote-play-v60

Uninstall remote play, install 5.5 from the download link on the wiki page, download and unzip the patcher, run the patcher exe to make 5.5 report that it is instead updated to 6.0, then controller inputs should work again.  The pre-race menu will fade out if no inputs are detected after about a minute, but will still be active and reappear upon hitting start on ClubmanSharp with a properly patched remote play.

**Comment by AvengerJ** [comment]
Thanks!  I wasn’t patching over version 5.5.  I did a quick rest and it seems to respond now.

Howard
