### ISSUE TITLE
According to the tutorial, it runs well, but the Controller Steering Sensitivity needs to be adjusted to 4.

### ISSUE THREAD

**Issue by smile-xuc** [ddm999/ClubmanSharp#58]
Operating environment: Windows 11
Console: PS5
Emulator client: PS remote Play and Chiaki
tunes: Mitsubishi GTO Twin Turbo '91 (Completely follow the tutorial to configure)

If the Controller Steering Sensitivity is set to 10, there will be situations where the tunnel direction is mistakenly hit and run off. However, if it is adjusted to 4, the overall score fluctuates between 1:16 and 1:25, which meets expectations.

Both clients perform similarly overall, But each has its own advantages and disadvantages.
- PS remote Play can run more stably for a longer time, but the score for each lap has greater fluctuations. 1:16~1:30+.
- Chiaki will freeze after running 30+ laps every time.

**Comment by ddm999** [comment]
Going to close this:
I suspect the controller sensitivity adjustment & PS Remote Play fluctuations just happens to help due to latency specific to your network rather than being a general issue.

Also to note, I am working on an adjustment to the pathing which may fix the issue regardless for most if not all networks by making the bot's steering more precise and/or providing a latency setting you can adjust - but I'm unsure when this will be complete.

**Comment by ddm999** [comment]
(i clicked the wrong button and this should probably count as "not planned" rather than "completed")
